# Generated by Django 6.0.7 on 2026-07-17 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='theme_color',
            field=models.CharField(blank=True, default='#2E3A66', help_text='のれん等に使う屋台のテーマ色（#RRGGBB）。未指定は藍。', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^(#[0-9A-Fa-f]{6})?$', '色は #RRGGBB 形式（7文字）で指定してください。')]),
        ),
    ]
