# Generated by Django 6.0.7 on 2026-07-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_stall_theme_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='在庫の増減数（補充は正、棚卸は差分）')),
                ('kind', models.CharField(choices=[('restock', '仕入れ補充'), ('stocktake', '棚卸調整')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
